### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by npadhu** [Hiblet/Log4NetCore#6]
Could you put an example project in the repository? I am having trouble following the instructions for logging in the class where I would be logging

**Comment by Hiblet** [comment]
Yes, no problem, good idea.  I will try to do this today.

**Comment by Hiblet** [comment]
OK, an example project is up.  

This demonstrates logging using both the slow MS facade functions, and the fast static functions.  I believe that MS are using reflection to record the class (and not cacheing the class name) so that is why their facade is slow.  If performance is important, you can add the class name yourself as a string and call the direct static functions.

Let me know if any of this is unclear or you need more info.

**Comment by npadhu** [comment]
Thanks for adding the solution. I see you  using both _logger and NZ01.Log4NetAsyncLog. Are you recommending NZ01.Log4NetAsyncLog over _logger?

**Comment by Hiblet** [comment]
If you use Dependency Injection for Unit Testing, and you use logging lightly, use _logger.  
If you want performance and simplicity and log inside loops, use direct access to Log4NetAsyncLog.  The difference is that _logger uses Microsoft's facade, which uses Reflection, which is costly (out of my control), and direct Log4NetAsyncLog does not, so it is vastly quicker.  
Both just add a log message to the concurrent queue, and you can mix and match both at any time.  The bonus of _logger is that it records the class.  You can do this yourself by including the class name in whatever text you write using Log4NetAsyncLog.
